### ISSUE TITLE
Postgresql 11 support notes

### ISSUE THREAD

**Issue by speedo-spin** [SchemaPlus/schema_plus_functions#1]
While we are on postgres v10, in postgres v11 `proisagg` was replaced with `prokind` in the system catalog pg_proc
This line will probably cause an issue on postgres upgrade: 
https://github.com/SchemaPlus/schema_plus_functions/blob/28a4d448829afdcbaeffdcaa052f8ff7c5ce3ae0/lib/schema_plus/functions/active_record/connection_adapters/postgresql_adapter.rb#L15

**Comment by ErvalhouS** [comment]
Just confirmed this issue
